name: MDAT
favicon: null
layout_spectrum: 0.8700583304744214
typography_spectrum: 0.6976697233039886
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6267792754806578
  lightness: 0.16309494362212718
  saturation: 0.24410062143579125
  rhythmicContrast: 0.39065066864714026
purpose: []
